# Generated by Django 5.1.6 on 2025-05-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=50, verbose_name='Позиция')),
                ('two_pointers', models.PositiveIntegerField(default=0, verbose_name='2-очковые')),
                ('three_pointers', models.PositiveIntegerField(default=0, verbose_name='3-очковые')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Общее количество очков')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер на майке')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='basketball/players/', verbose_name='Фото игрока')),
                ('avg_points', models.FloatField(default=0, verbose_name='Средние очки за игру')),
            ],
        ),
    ]
