# Generated by Django 5.1.6 on 2025-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('points_scored', models.PositiveIntegerField(default=0, verbose_name='Забитые очки')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
        ),
    ]
