# Generated by Django 5.1.6 on 2025-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='notes',
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
