# Generated by Django 5.1.6 on 2025-05-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_remove_training_notes_training_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('intensity', models.PositiveSmallIntegerField(choices=[(0, 'Нет данных'), (1, 'Мало активности'), (2, 'Средняя активность'), (3, 'Хорошая тренировка'), (4, 'Отличная тренировка')], default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
