# Generated by Django 5.1.6 on 2025-05-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_basketballsession_delete_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballsession',
            name='intensity',
        ),
        migrations.AddField(
            model_name='basketballsession',
            name='points_scored',
            field=models.PositiveIntegerField(default=0, verbose_name='Набрано очков'),
        ),
    ]
