# Generated by Django 5.1.6 on 2025-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_remove_basketballsession_intensity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('two_pointers', models.PositiveIntegerField(default=0, verbose_name='2-очковые')),
                ('three_pointers', models.PositiveIntegerField(default=0, verbose_name='3-очковые')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Общее число очков')),
            ],
        ),
        migrations.DeleteModel(
            name='BasketballSession',
        ),
    ]
