# Generated by Django 5.1.6 on 2025-05-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_basketballgame_delete_basketballsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avg_points',
            field=models.FloatField(blank=True, default=0, verbose_name='Средние очки за игру'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_points',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Общее количество очков'),
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_pointers', models.PositiveIntegerField(default=0)),
                ('three_pointers', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.basketballgame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.player')),
            ],
        ),
    ]
