# Generated by Django 5.1.6 on 2025-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название песни')),
                ('artist', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('chords_link', models.URLField(verbose_name='Ссылка на аккорды')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
