# Generated by Django 5.1.6 on 2025-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='URL медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
