# Generated by Django 5.1.6 on 2025-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_telegrampost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrampost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='telegrampost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
    ]
