# Generated by Django 5.1.6 on 2025-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_remove_telegrampost_media_url_telegrampost_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampost',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
