# Generated by Django 5.1.6 on 2025-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_alter_telegrampost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrampost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_posts/', verbose_name='Изображение'),
        ),
    ]
