# Generated by Django 5.1.6 on 2025-06-04 10:09
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('color', models.CharField(default='gray', max_length=50, verbose_name='Цвет (HEX или название)')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(default='gray', max_length=50, verbose_name='Цвет (HEX или название)')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('status', models.CharField(
                    choices=[('to_do', 'Задача'), ('in_progress', 'В работе'), ('on_review', 'На проверке'), ('done', 'Выполнено')],
                    default='to_do',
                    max_length=20,
                    verbose_name='Статус'
                )),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Приоритетная')),
                ('category', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='kanban.category',
                    verbose_name='Категория'
                )),
                ('tags', models.ManyToManyField(
                    blank=True,
                    to='kanban.tag',
                    verbose_name='Теги'
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь'
                )),
            ],
        ),
    ]