# Generated by Django 5.1.6 on 2025-02-26 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsnow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snowboard_images/'),
        ),
        migrations.AlterField(
            model_name='postsnow',
            name='content',
            field=models.TextField(verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='postsnow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания поста'),
        ),
        migrations.AlterField(
            model_name='postsnow',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время публикации поста'),
        ),
        migrations.AlterField(
            model_name='postsnow',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок поста'),
        ),
    ]
