# Generated by Django 5.1.6 on 2025-02-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0002_postsnow_image_alter_postsnow_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsnow',
            options={'ordering': ['-published_at']},
        ),
    ]
