# Generated by Django 5.1.6 on 2025-02-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard', '0003_alter_postsnow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsnow',
            options={},
        ),
    ]
