# Generated by Django 5.1.6 on 2025-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='intensity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет данных'), (1, 'Лёгкая'), (2, 'Средняя'), (3, 'Хорошая'), (4, 'Интенсивная')], default=0),
        ),
    ]
