# Generated by Django 5.1.6 on 2025-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_training_intensity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AddField(
            model_name='training',
            name='dips_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Брусья максимум за подход'),
        ),
        migrations.AddField(
            model_name='training',
            name='dips_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Брусья всего за тренировку'),
        ),
        migrations.AddField(
            model_name='training',
            name='pull_ups_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подтягивания максимум за подход'),
        ),
        migrations.AddField(
            model_name='training',
            name='pull_ups_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подтягивания всего за тренировку'),
        ),
        migrations.AddField(
            model_name='training',
            name='push_ups_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отжимания максимум за подход'),
        ),
        migrations.AddField(
            model_name='training',
            name='push_ups_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отжимания всего за тренировку'),
        ),
        migrations.AddField(
            model_name='training',
            name='run_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Бег: дистанция (км)'),
        ),
        migrations.AddField(
            model_name='training',
            name='run_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Бег: время (мин:сек)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='training',
            name='intensity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет данных'), (1, 'Лёгкая'), (2, 'Средняя'), (3, 'Хорошая'), (4, 'Интенсивная')], default=0, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='training',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
