# Generated by Django 5.1.6 on 2025-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_training_options_training_dips_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='run_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Время бега'),
        ),
    ]
